name = "JuliaProject"
uuid = "b0c4f35d-f4f0-47bd-8054-f37f4c5ce7b1"
authors = ["Chris du Plessis"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[compat]
Documenter = "0.27"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
